redis:
  container_name: action-cable-chat-redis
  image: redis:latest
  ports:
    - "6379"

app:
  container_name: action-cable-chat-app
  build: .
  dockerfile: Dockerfile
  ports:
    - "5000:5000"
  volumes:
    - ".:/webapp"
  env_file:
    - ./.env.docker_compose
  links:
    - redis
